;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")
((nil . ((standard-indent . 2)
         (c-basic-offset . 2)
         (coffee-tab-width . 2)
         (javascript-indent-level . 2)
         (typescript-indent-level . 2)
         (js-indent-level . 2)
         (js3-indent-level . 2)
         (js-jsx-indent-level . 2)
         (sgml-basic-offset . 2)
         (web-mode-markup-indent-offset . 2)
         (web-mode-css-indent-offset . 2)
         (web-mode-code-indent-offset . 2)
         (css-indent-offset . 2)
         (evil-shift-width . 2)
         (my/lsp-file-watch-ignored-directories . ("[/\\\\]3rdParty"
                                                   "[/\\\\]generated"))
         (lsp-eslint-rules-customizations . [((rule . "prettier/prettier") (severity . "info"))])
         (lsp-typescript-format-enable . nil)
         ))
 (typescript-tsx-mode . ((dash-at-point-docset . "_,ts,react,js")
                      (lsp-typescript-preferences-quote-style . "double")))
 (typescript-mode . ((dash-at-point-docset . "_,ts,react,js")
                     (lsp-typescript-preferences-quote-style . "double")))
 (javascript-mode . ((dash-at-point-docset . "_,ts,react,js")
                     (lsp-javascript-preferences-quote-style . "double")))
 (json-mode . ((mode . jsonc)
               (truncate-lines . t)))
 (magit-status-mode . ((magit-todos-exclude-globs . (".git/" "3rdParty" "generated")))))
